### ISSUE TITLE
Can help?

### ISSUE THREAD

**Issue by trallard** [harlecin/serverless#1]
Hi I just saw the project as funded by the RConsortium. Great news 🎆 I would like to get involved if possible not only as an Azure advocate but also as an R user and a community member. 

I am unsure how much work/planning has been done  but I would certainly like to chip in!

**Comment by iainmwallace** [comment]
Also happy to help!

**Comment by harlecin** [comment]
Hey there:)

Awesome, any help is greatly appreciated! 

So far, we did a few small PoCs to test AWS Lambda and Azure Functions. Lambda is working after a fashion, but there are some issues when it comes to using compiled libraries (e.g. XGBoost, etc). Our plan is to create a backlog on Github over the next couple of days. We have a few ideas regarding architecture that I would love to get feedback on:)

Regarding Azure Functions: @trallard: From what we saw sofar AzFunctions depends on us being able to build/extend the gRPC package from Neal Fultz to include bidirectional streaming. I also saw that custom docker images with Linux runtimes are in public preview now, so that might a route worth exploring. If you have ideas/suggestions how we can approach custom runtimes on Azure that would be brilliant:) With runtime version 1, we used to be able to simply upload a binary as a site-extenison and call it using e.g. Powershell as a wrapper (see [here](https://medium.com/@cednewein/r-microservices-on-microsoft-azure-part-1-ff934380e5a1) for an example). That is quite similar to how deployments work on AWS Lambda, but as far as I understood, it does not support consumption plans? 

I have a busy time at work at the moment, so my response time can be a bit slow I am afraid:(

I will try to get documentation of everything we already tried uploaded asap and create a small project plan:)

**Comment by dgyurko** [comment]
Hi,

As someone who likes to work with R and also AWS Lambda I welcome the idea! In case you need some help I would like to help out as well.

**Comment by harlecin** [comment]
You are very welcome!

AWS Lambda has a few constraints that we need to take care of (mostly in
connection with compiled packages) so any help is appreciated:)

I will be on vacation starting April and my plan is to put all the stuff we
already tried and our ideas on Github.

Currently, my colleagues and I are leaning towards Amazon Fargate / Azure
Container Instances, because it would make it easier for non-technical
people to do one-click deployments without having to manually compile
packages for the Linux distro used by Lambda.

Best

**Comment by trallard** [comment]
Great if focused on Azure I am sure I can be of much more help 🙂 keep us posted
